feat: major updates as new laptop arrived; switching to zsh possibly

diff --git a/bin/dotfiles b/bin/dotfiles
--- a/bin/dotfiles
+++ b/bin/dotfiles
@@ -3,7 +3,7 @@
 BIN_NAME=$(basename "$0")
 COMMAND_NAME=$1
 
-sub_help () {
+sub_help() {
   echo "Usage: $BIN_NAME <command>"
   echo
   echo "Commands:"
@@ -16,15 +16,15 @@ sub_help () {
   echo "   update           Update packages and pkg managers (OS, brew, npm, gem)"
 }
 
-sub_edit () {
+sub_edit() {
   sh -c "$DOTFILES_IDE $DOTFILES_DIR"
 }
 
-sub_test () {
+sub_test() {
   bats "$DOTFILES_DIR"/test/*.bats
 }
 
-sub_update () {
+sub_update() {
   sudo softwareupdate -i -a
   brew update
   brew upgrade
@@ -32,37 +32,41 @@ sub_update () {
   npm update -g
   gem update --system
   gem update
-  pip install --upgrade pip && pip freeze --local | grep -v '^\-e' | cut -d = -f 1  | xargs -n1 pip install -U
+  pip install --upgrade pip && pip freeze --local | grep -v '^\-e' | cut -d = -f 1 | xargs -n1 pip install -U
 }
 
-sub_clean () {
+sub_clean() {
   brew cleanup
   gem cleanup
-  . "$NVM_DIR/nvm.sh"; nvm cache clear
+  # shellcheck disable=SC1091
+  . "$NVM_DIR/nvm.sh"
+  nvm cache clear
 }
 
-sub_macos () {
+sub_macos() {
   for DEFAULTS_FILE in "${DOTFILES_DIR}"/macos/defaults*.sh; do
+    # shellcheck disable=SC1090
     echo "Applying ${DEFAULTS_FILE}" && . "${DEFAULTS_FILE}"
   done
   echo "Done. Some changes may require a logout/restart to take effect."
 }
 
-sub_dock () {
+sub_dock() {
+  # shellcheck disable=SC1091
   . "${DOTFILES_DIR}/macos/dock.sh" && echo "Dock reloaded."
 }
 
 case $COMMAND_NAME in
-  "" | "-h" | "--help")
+"" | "-h" | "--help")
+  sub_help
+  ;;
+*)
+  shift
+  sub_"${COMMAND_NAME}" "$@"
+  if [ $? = 127 ]; then
+    echo "'$COMMAND_NAME' is not a known command or has errors." >&2
     sub_help
-    ;;
-  *)
-    shift
-    sub_${COMMAND_NAME} $@
-    if [ $? = 127 ]; then
-      echo "'$COMMAND_NAME' is not a known command or has errors." >&2
-      sub_help
-      exit 1
-    fi
-    ;;
+    exit 1
+  fi
+  ;;
 esac
